### ISSUE TITLE
Add new elasticSearch nodes

### ISSUE THREAD

**Issue by NT-me** [AlessandroRinaudo/elastic-search-project#10]
It's can be very cool if we got few nodes. Decentralization is one of the most important es's features

We need to modify docker-compose and add nodes, touchy part is kibana-es connection.

Python connection is very simple :
https://elasticsearch-py.readthedocs.io/en/v7.15.1/api.html#elasticsearch.Elasticsearch 
=>
```python
# connect to localhost directly and another node using SSL on port 443
# and an url_prefix. Note that ``port`` needs to be an int.
es = Elasticsearch([
    {'host': 'localhost'},
    {'host': 'othernode', 'port': 443, 'url_prefix': 'es', 'use_ssl': True},
])
```

Example :
https://github.com/davidbkemp/advanced-elasticsearch-training/blob/master/docker-compose.multi-node.yml

From first es TME:
```yaml
 es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
    - elastic
   ```
